## Exercise 1

In [2]:
import numpy as np

In [30]:
np.sum([1, 2])

3

In [10]:
%%timeit
np.sum(np.random.rand(100000000))

1.17 s ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%%timeit
np.random.rand(100000000).sum()

1.17 s ± 45.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%%timeit
np.random.rand(100000000,1).sum()

1.27 s ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Ecercise 2

In [24]:
def ravel(row, col, n_rows, n_cols):
    return row*n_cols + col

In [25]:
ravel(2,3,4,4)

11

In [26]:
ravel(2, 3, n_rows=4, n_cols=8)

19

In [27]:
ravel(0, 0, n_rows=1, n_cols=1)

0

In [28]:
ravel(3, 3, n_rows=4, n_cols=4)

15

In [29]:
ravel(3_465, 18_923, n_rows=10_000, n_cols=20_000)

69318923

## Exercise 3

In [33]:
from numpy.lib.stride_tricks import as_strided
def transpose(a):
    return as_strided(a, shape=a.shape[::-1], strides=a.strides[::-1])

In [35]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print('Before transpose:')
print(a)
print('After transpose:')
print(transpose(a))

Before transpose:
[[1 2 3]
 [4 5 6]]
After transpose:
[[1 4]
 [2 5]
 [3 6]]


In [36]:
from numpy.lib.stride_tricks import as_strided
a = np.array([1., 2., 3., 4., 5.])
as_strided(a, shape=(5, 100_000_000_000), strides=(8, 0))

array([[1., 1., 1., ..., 1., 1., 1.],
       [2., 2., 2., ..., 2., 2., 2.],
       [3., 3., 3., ..., 3., 3., 3.],
       [4., 4., 4., ..., 4., 4., 4.],
       [5., 5., 5., ..., 5., 5., 5.]])